apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  selector:
    matchLabels:
      run: flask-demo
  replicas: 3
  template:
    metadata:
      labels:
        run: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: gcr.io/{your-project-id}/flask-demo:0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  labels:
    run: flask-demo
spec:
  ports:
  - port: 8080
  selector:
    run: flask-demo